using FinSight.Data;
using FinSight.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.HttpOverrides;
using Stripe;

var builder = WebApplication.CreateBuilder(args);

builder.Logging.ClearProviders();
builder.Logging.AddConsole();
builder.Logging.AddDebug();
builder.Logging.AddFilter("Microsoft.AspNetCore.DataProtection", LogLevel.Error);

// Add services to the container.
builder.Services.AddControllersWithViews();
var dataProtectionKeysPath = Path.Combine(builder.Environment.ContentRootPath, "App_Data", "DataProtection-Keys");
Directory.CreateDirectory(dataProtectionKeysPath);
builder.Services.AddDataProtection()
    .PersistKeysToFileSystem(new DirectoryInfo(dataProtectionKeysPath));
builder.Services.AddScoped<AuditLogService>();
builder.Services.AddScoped<NotificationService>();
builder.Services.AddScoped<TwoFactorService>();
builder.Services.AddHttpClient<AlphaVantageService>();
builder.Services.AddScoped<AlphaVantageService>();

// Configure Forwarded Headers for Cloudflare Reverse Proxy
builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
    // Clear the known networks and proxies so it accepts headers from Cloudflare
    options.KnownNetworks.Clear();
    options.KnownProxies.Clear();
});

// Register EF Core DbContext with SQL Server
// UseCompatibilityLevel(120) prevents the 'WITH' SqlException on older SQL Server instances
// that do not support the OPENJSON syntax generated by EF Core 8+ for .Contains() queries.
builder.Services.AddDbContext<FinSightDbContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection"),
        sqlOptions => sqlOptions.UseCompatibilityLevel(120)));

// Add Session support with hardened cookies
builder.Services.AddDistributedMemoryCache();
builder.Services.AddSession(options =>
{
    options.IdleTimeout = TimeSpan.FromMinutes(30);
    options.Cookie.HttpOnly = true;                          // Prevent JS access
    options.Cookie.SecurePolicy = CookieSecurePolicy.SameAsRequest; // Matches request scheme
    options.Cookie.SameSite = SameSiteMode.Lax;              // Allow cookie on redirect back from Stripe
    options.Cookie.IsEssential = true;
    options.Cookie.Name = ".FinSight.Session";               // Custom name (no framework fingerprinting)
});

var app = builder.Build();

// Configure Stripe API Key
StripeConfiguration.ApiKey = builder.Configuration.GetSection("Stripe")["SecretKey"];

// ----- SEED DATABASE -----
using (var scope = app.Services.CreateScope())
{
    var services = scope.ServiceProvider;
    try
    {
        var context = services.GetRequiredService<FinSightDbContext>();
        var logger = services.GetRequiredService<ILogger<Program>>();
        
        // Automatically apply pending migrations on startup
        await context.Database.MigrateAsync();
        
        await DbInitializer.InitializeAsync(context, logger, builder.Configuration);
    }
    catch (Exception ex)
    {
        var logger = services.GetRequiredService<ILogger<Program>>();
        logger.LogError(ex, "Failed executing DbInitializer during app startup.");
    }
}

// Configure the HTTP request pipeline.
app.UseForwardedHeaders(); // Must be very early in the pipeline

// Set Default Culture to en-PH for Peso Currency
var defaultCulture = new System.Globalization.CultureInfo("en-PH");
var localizationOptions = new RequestLocalizationOptions
{
    DefaultRequestCulture = new Microsoft.AspNetCore.Localization.RequestCulture(defaultCulture),
    SupportedCultures = new List<System.Globalization.CultureInfo> { defaultCulture },
    SupportedUICultures = new List<System.Globalization.CultureInfo> { defaultCulture }
};
app.UseRequestLocalization(localizationOptions);

if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage(); // Show detailed errors in dev only
}
else
{
    app.UseExceptionHandler("/Home/Error");
    app.UseStatusCodePagesWithReExecute("/Home/Error", "?statusCode={0}");
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseSession(); // Must come before UseAuthorization
app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

await app.RunAsync();
