using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Collections.Generic;
using System;

namespace FinSight.Services
{
    public class PdfReportGenerator
    {
        public static byte[] GenerateReport(string reportTitle, string tenantName, string generatedBy, List<string> headers, List<List<string>> dataRows)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4.Landscape());
                    page.Margin(1, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(10).FontFamily(Fonts.Arial));

                    page.Header().Element(c => ComposeHeader(c, reportTitle, tenantName));
                    page.Content().Element(c => ComposeContent(c, headers, dataRows));
                    page.Footer().Element(c => ComposeFooter(c, generatedBy));
                });
            });

            return document.GeneratePdf();
        }

        private static void ComposeHeader(IContainer container, string title, string tenantName)
        {
            container.Row(row =>
            {
                row.RelativeItem().Column(column =>
                {
                    column.Item().Text(tenantName).FontSize(18).SemiBold().FontColor(Colors.Blue.Darken2);
                    column.Item().Text(title).FontSize(14).SemiBold().FontColor(Colors.Grey.Darken3);
                });
                row.ConstantItem(100).AlignRight().Text(DateTime.Now.ToString("MMM dd, yyyy HH:mm")).FontSize(9);
            });
        }

        private static void ComposeContent(IContainer container, List<string> headers, List<List<string>> dataRows)
        {
            container.PaddingVertical(1, Unit.Centimetre).Table(table =>
            {
                // Columns
                table.ColumnsDefinition(columns =>
                {
                    for (int i = 0; i < headers.Count; i++)
                    {
                        if (i == 0) columns.RelativeColumn(2);
                        else columns.RelativeColumn();
                    }
                });

                // Header
                table.Header(header =>
                {
                    foreach (var h in headers)
                    {
                        header.Cell().Background(Colors.Grey.Lighten3)
                            .BorderBottom(1).BorderColor(Colors.Grey.Darken2)
                            .PaddingVertical(5).PaddingHorizontal(5)
                            .Text(h).SemiBold();
                    }
                });

                // Rows
                foreach (var row in dataRows)
                {
                    for (int i = 0; i < row.Count; i++)
                    {
                        table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten2)
                            .PaddingVertical(5).PaddingHorizontal(5)
                            .Text(row[i]).FontSize(9);
                    }
                }
            });
        }

        private static void ComposeFooter(IContainer container, string generatedBy)
        {
            container.Row(row =>
            {
                row.RelativeItem().Text($"Generated by: {generatedBy}").FontSize(8).FontColor(Colors.Grey.Medium);
                row.RelativeItem().AlignRight().Text(x =>
                {
                    x.Span("Page ");
                    x.CurrentPageNumber();
                    x.Span(" of ");
                    x.TotalPages();
                });
            });
        }
    }
}
